openapi: 3.1.0
info:
  title: Mini Teacher Service
  version: 0.0.0
tags:
  - name: Years
  - name: Classes
  - name: Students
paths:
  /class:
    get:
      operationId: Classes_list
      description: List classes in a year
      parameters:
        - name: yearId
          in: query
          required: true
          schema:
            type: string
          explode: false
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Class'
                  error:
                    type: string
      tags:
        - Classes
    post:
      operationId: Classes_create
      description: Create a class
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Class'
                  error:
                    type: string
      tags:
        - Classes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClassBody'
  /class/{classId}:
    put:
      operationId: Classes_update
      description: Update a class
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Class'
                  error:
                    type: string
      tags:
        - Classes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClassBody'
    delete:
      operationId: Classes_delete
      description: Delete a class
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Classes
    get:
      operationId: Classes_getById
      parameters:
        - name: classId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Class'
                  error:
                    type: string
      tags:
        - Classes
  /student:
    get:
      operationId: Students_list
      description: List students in a class
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Student'
                  error:
                    type: string
      tags:
        - Students
    post:
      operationId: Students_create
      description: Create a student
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Student'
                  error:
                    type: string
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudentBody'
  /student/{studentId}:
    put:
      operationId: Students_update
      description: Update a student
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Student'
                  error:
                    type: string
      tags:
        - Students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStudentBody'
    delete:
      operationId: Students_delete
      description: Delete a student
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Students
    get:
      operationId: Students_getById
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Student'
                  error:
                    type: string
      tags:
        - Students
  /year:
    get:
      operationId: Years_list
      description: List years
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
    post:
      operationId: Years_create
      description: Create a year
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateYearBody'
  /year/{yearId}:
    put:
      operationId: Years_update
      description: Update a year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateYearBody'
    patch:
      operationId: Years_setActive
      description: Set active year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Years
    delete:
      operationId: Years_delete
      description: Delete a year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Years
components:
  schemas:
    Class:
      type: object
      required:
        - id
        - year
        - name
        - subject
        - isActive
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        year:
          type: string
        name:
          type: string
        subject:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateClassBody:
      type: object
      required:
        - year
        - name
        - subject
      properties:
        year:
          type: string
        name:
          type: string
        subject:
          type: string
        isActive:
          type: boolean
    CreateStudentBody:
      type: object
      required:
        - code
        - firstName
        - lastName
      properties:
        code:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        nickname:
          type: string
    CreateYearBody:
      type: object
      required:
        - year
        - term
      properties:
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
    EmptyData:
      type: object
    Student:
      type: object
      required:
        - id
        - teacher
        - code
        - firstName
        - lastName
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        teacher:
          type: string
        code:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        nickname:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UpdateClassBody:
      type: object
      properties:
        year:
          type: string
        name:
          type: string
        subject:
          type: string
        isActive:
          type: boolean
        updatedAt:
          type: string
          format: date-time
    UpdateStudentBody:
      type: object
      properties:
        code:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        nickname:
          type: string
    UpdateYearBody:
      type: object
      properties:
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
        updatedAt:
          type: string
          format: date-time
    Year:
      type: object
      required:
        - id
        - user
        - year
        - term
        - isActive
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
