openapi: 3.1.0
info:
  title: Mini Teacher Service
  version: 0.0.0
tags:
  - name: Years
paths:
  /api/year:
    get:
      operationId: Years_list
      description: List years
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
    post:
      operationId: Years_create
      description: Create a year
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Year'
  /api/year/{id}:
    get:
      operationId: Years_read
      description: Read year
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
    patch:
      operationId: Years_update
      description: Update a year
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/YearMergePatchUpdate'
    delete:
      operationId: Years_delete
      description: Delete a year
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Years
  /api/year/{id}/analyze:
    post:
      operationId: Years_analyze
      description: Analyze a year
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/AnalyzeResult'
                  error:
                    type: string
      tags:
        - Years
components:
  schemas:
    AnalyzeResult:
      type: object
      required:
        - id
        - analysis
      properties:
        id:
          type: string
        analysis:
          type: string
    EmptyData:
      type: object
    Year:
      type: object
      required:
        - id
        - user
        - year
        - term
        - isActive
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    YearMergePatchUpdate:
      type: object
      properties:
        id:
          type: string
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      description: ''
