openapi: 3.1.0
info:
  title: Mini Teacher Service
  version: 0.0.0
tags:
  - name: Years
paths:
  /year:
    get:
      operationId: Years_list
      description: List years
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
    post:
      operationId: Years_create
      description: Create a year
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateYearBody'
  /year/{yearId}:
    put:
      operationId: Years_update
      description: Update a year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Year'
                  error:
                    type: string
      tags:
        - Years
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateYearBody'
    patch:
      operationId: Years_setActive
      description: Set active year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Years
    delete:
      operationId: Years_delete
      description: Delete a year
      parameters:
        - name: yearId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/EmptyData'
                  error:
                    type: string
      tags:
        - Years
components:
  schemas:
    CreateYearBody:
      type: object
      required:
        - year
        - term
      properties:
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
    EmptyData:
      type: object
    UpdateYearBody:
      type: object
      properties:
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
        updatedAt:
          type: string
          format: date-time
    Year:
      type: object
      required:
        - id
        - user
        - year
        - term
        - isActive
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
        user:
          type: string
        year:
          type: integer
          format: int32
        term:
          type: integer
          format: int32
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
